### ISSUE TITLE
no timeout for genereted QR

### ISSUE THREAD

**Issue by hernanjls** [aditya5660/whatsapp-api#1]
Hi, I think that this is script is very good but I am testing and see that when the generated QR code is not confirmed in the device, this will be have an timeout, because in this moment for not confirmed qrs the sever is re-generate again , thst is good for some time but not forever, will be put some class of timeout for not regenerate always

**Comment by aditya5660** [comment]
do you have an idea for handling timeout issue? please give a pull request
